import { Address } from "../models/address";

export const addressList: Address[] = [
  {
    postcode: "AL6 9LF",
    latitude: 51.8325439,
    longitude: -0.2134126,
    formatted_address: [
      "Welwyn Hall Management Ltd",
      "32 Welwyn Hall Gardens",
      "",
      "Welwyn",
      "Hertfordshire",
    ],
    thoroughfare: "Welwyn Hall Gardens",
    building_name: "",
    sub_building_name: "Welwyn Hall Management Ltd",
    sub_building_number: "",
    building_number: "32",
    line_1: "Welwyn Hall Management Ltd",
    line_2: "32 Welwyn Hall Gardens",
    line_3: "",
    line_4: "",
    locality: "",
    town_or_city: "Welwyn",
    county: "Hertfordshire",
    district: "Welwyn Hatfield",
    country: "England",
    residential: false,
    uid: "c442e69b-72a6-431f-8aeb-2ff81d53fd89",
  },
  {
    postcode: "IM2 2QZ",
    latitude: 54.15386059999999,
    longitude: -4.5356102,
    formatted_address: [
      "Bibby Ship Management Ltd",
      "Compass House",
      "Isle of Man Business Park",
      "Douglas, Isle of Man",
      "",
    ],
    thoroughfare: "Isle of Man Business Park",
    building_name: "Compass House",
    sub_building_name: "Bibby Ship Management Ltd",
    sub_building_number: "",
    building_number: "",
    line_1: "Bibby Ship Management Ltd",
    line_2: "Compass House",
    line_3: "Isle of Man Business Park",
    line_4: "",
    locality: "Douglas",
    town_or_city: "Isle of Man",
    county: "",
    district: "",
    country: "Isle of Man",
    residential: false,
    uid: "c40e69b0-ec2a-4253-862a-4c71f87e0c7e",
  },
  {
    postcode: "SE17 2TN",
    latitude: 51.487158,
    longitude: -0.091571,
    formatted_address: ["Flat 1", "Woodsford", "Portland Street", "London", ""],
    thoroughfare: "Portland Street",
    building_name: "Woodsford",
    sub_building_name: "Flat 1",
    sub_building_number: "1",
    building_number: "",
    line_1: "Flat 1",
    line_2: "Woodsford",
    line_3: "Portland Street",
    line_4: "",
    locality: "",
    town_or_city: "London",
    county: "",
    district: "Southwark",
    country: "England",
    residential: true,
    uid: "93c4d789-8a85-4d05-81b5-a37a375fcd39",
  },
];
